#---------------------------------------------------------------------
# Global settings
#---------------------------------------------------------------------
global
  # setup logging and force level to debug. Logs require rsyslog be setup.
  chroot /var/lib/haproxy
  log /dev/log local0 debug

  # maximum number of connections allowed
  maxconn 10000

  # turn on stats unix socket
  stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
  stats timeout 30s

  # user and group haproxy will run as
  user haproxy
  group haproxy

#---------------------------------------------------------------------
# common defaults that all the 'listen' and 'backend' sections will
# use if not designated in their block
#---------------------------------------------------------------------
defaults
  default-server init-addr last,libc,none
  log global
  mode http

  option httplog
  option forwardfor

  timeout connect 10s
  timeout client 60s
  timeout server 60s
  timeout tunnel 1h

#---------------------------------------------------------------------
# FrontEnd Configuration
#---------------------------------------------------------------------
frontend frontend-1
  bind *:80 name web

  use_backend backend-1

  # default traffic to platform
  default_backend backend-1

#---------------------------------------------------------------------
# BackEnd Platform Configuration
#---------------------------------------------------------------------
backend backend-1
  balance roundrobin

  option httpchk GET /

  # configure platform instances
  server nginx_1 NGINX_1_HOST:80 
  server nginx_2 NGINX_2_HOST:80

#---------------------------------------------------------------------
#HAProxy Monitoring Config
#---------------------------------------------------------------------
listen stats
  bind *:1936
  mode http
  option forwardfor
  option httpclose
  stats enable
  stats uri /
  stats refresh 5s
  stats show-legends
  stats realm Haproxy\ Statistics